server {
    listen 80;
    server_name site1.local;
    return 301 https://$host$request_uri;
}

server {
    listen 80;
    server_name site2.local;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name site1.local;

    ssl_certificate /etc/nginx/ssl/site1.crt;
    ssl_certificate_key /etc/nginx/ssl/site1.key;

    location / {
        proxy_pass http://site1-web;
    }
}

server {
    listen 443 ssl;
    server_name site2.local;

    ssl_certificate /etc/nginx/ssl/site1.crt;
    ssl_certificate_key /etc/nginx/ssl/site1.key;

    location / {
        proxy_pass http://site2-web;
    }
}
